from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from reportlab.lib.colors import HexColor
from datetime import datetime
import io

# Colors
PRIMARY = HexColor("#111827")
MUTED = HexColor("#6b7280")
ACCENT = HexColor("#2563eb")
GOOD = HexColor("#059669")
BAD = HexColor("#dc2626")

LEFT = 45
RIGHT = 550
TOP = 805
BOTTOM = 60
LINE = 14


def build_pdf(data):
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    w, h = A4
    y = TOP

    def ensure(space=40):
        nonlocal y
        if y < BOTTOM + space:
            c.showPage()
            y = TOP

    def hr():
        nonlocal y
        ensure(20)
        c.setStrokeColor(MUTED)
        c.line(LEFT, y, RIGHT, y)
        y -= 10

    # ================= HEADER =================
    c.setFont("Helvetica-Bold", 20)
    c.setFillColor(PRIMARY)
    c.drawString(LEFT, y, "Web Security Scan Report")

    c.setFont("Helvetica-Bold", 22)
    c.setFillColor(ACCENT)
    c.drawRightString(RIGHT, y, f"{data.get('score', '--')}/100")

    y -= 26
    c.setFont("Helvetica", 10)
    c.setFillColor(MUTED)
    c.drawString(LEFT, y, f"Target: {data.get('target', '-')}")
    c.drawRightString(
        RIGHT,
        y,
        datetime.utcnow().strftime("%d %b %Y %H:%M UTC")
    )

    y -= 12
    hr()

    # ================= EXECUTIVE SUMMARY =================
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(PRIMARY)
    c.drawString(LEFT, y, "Executive Summary")
    y -= 10
    hr()

    tls = data.get("tls", {})
    headers = data.get("headers", {})

    exec_rows = [
        ("TLS Version", tls.get("tls_version", "-")),
        ("Certificate Issuer", tls.get("issuer", "-")),
        ("Content Security Policy", data.get("csp_status", "Unknown")),
        ("Security Headers", f"{sum(headers.values())}/{len(headers)}"),
        ("CDN / Proxy", data.get("cdn", "Unknown")),
    ]

    c.setFont("Helvetica", 10)
    for k, v in exec_rows:
        ensure()
        c.setFillColor(PRIMARY)
        c.drawString(LEFT + 5, y, k)
        c.setFillColor(MUTED)
        c.drawString(260, y, str(v))
        y -= LINE

    y -= 8

    # ================= TLS DETAILS =================
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(PRIMARY)
    c.drawString(LEFT, y, "TLS / SSL Configuration")
    y -= 10
    hr()

    tls_rows = [
        ("Issuer", tls.get("issuer", "-")),
        ("Valid From", tls.get("valid_from", "-")),
        ("Valid To", tls.get("valid_to", "-")),
        ("Days Remaining", tls.get("days_remaining", "-")),
        ("TLS Version", tls.get("tls_version", "-")),
    ]

    c.setFont("Helvetica", 10)
    for k, v in tls_rows:
        ensure()
        c.setFillColor(PRIMARY)
        c.drawString(LEFT + 5, y, k)
        c.setFillColor(MUTED)
        c.drawString(260, y, str(v))
        y -= LINE

    y -= 8

    # ================= DNS PANEL =================
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(PRIMARY)
    c.drawString(LEFT, y, "DNS Resolution & Network Location")
    y -= 10
    hr()

    dns = data.get("dns", {})
    results = dns.get("results", [])

    c.setFont("Helvetica", 10)
    for r in results:
        ensure(50)

        c.setFillColor(PRIMARY)
        c.drawString(LEFT + 5, y, r.get("resolver", "-"))
        y -= LINE

        c.setFillColor(MUTED)
        c.drawString(LEFT + 20, y, f"Location: {r.get('location', '-')}")
        c.drawString(300, y, f"Provider: {r.get('provider', '-')}")
        y -= LINE

        ips = ", ".join(r.get("ips", [])) or "-"
        c.drawString(LEFT + 20, y, f"IPs: {ips}")
        y -= LINE + 6

    y -= 6

    # ================= HEADERS =================
    c.setFont("Helvetica-Bold", 12)
    c.setFillColor(PRIMARY)
    c.drawString(LEFT, y, "HTTP Security Headers")
    y -= 10
    hr()

    c.setFont("Helvetica", 10)
    for h, present in headers.items():
        ensure()
        c.setFillColor(PRIMARY)
        c.drawString(LEFT + 5, y, h)
        c.setFillColor(GOOD if present else BAD)
        c.drawRightString(RIGHT, y, "Present" if present else "Missing")
        y -= LINE

    # ================= FOOTER =================
    c.setFont("Helvetica", 8)
    c.setFillColor(MUTED)
    c.drawCentredString(
        w / 2,
        25,
        "Generated by WebGuard • Automated Web Security Scanner"
    )

    c.showPage()
    c.save()
    buf.seek(0)
    return buf

